name: rayee
description: A smart-glasses companion app for blind and visually-impaired users.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core Logic
  web_socket_channel: ^3.0.0
  sound_stream: ^0.3.0
  flutter_mjpeg: ^2.0.0
  permission_handler: ^11.0.0
  provider: ^6.0.0
  shared_preferences: ^2.2.0
  google_fonts: ^4.0.4

  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
